### ISSUE TITLE
Error running ../configure on macOS Ventura

### ISSUE THREAD

**Issue by TylerJaacks** [devos50/qemu#14]
```../configure```

```
Program scripts/minikconf.py found: YES (/usr/local/opt/python@3.11/bin/python3.11 /Users/tylerjaacks/Desktop/qemu/scripts/minikconf.py)
Configuring aarch64-softmmu-config-target.h using configuration
Configuring aarch64-softmmu-config-devices.mak with command
Reading depfile: /Users/tylerjaacks/Desktop/qemu/build/meson-private/aarch64-softmmu-config-devices.mak.d
Configuring aarch64-softmmu-config-devices.h using configuration
Configuring alpha-softmmu-config-target.h using configuration
Configuring alpha-softmmu-config-devices.mak with command

../meson.build:1984:4: ERROR: Command "/usr/local/opt/python@3.11/bin/python3.11 /Users/tylerjaacks/Desktop/qemu/scripts/minikconf.py --defconfig alpha-softmmu-config-devices.mak /Users/tylerjaacks/Desktop/qemu/build/meson-private/alpha-softmmu-config-devices.mak.d /Users/tylerjaacks/Desktop/qemu/configs/devices/alpha-softmmu/default.mak /Users/tylerjaacks/Desktop/qemu/Kconfig CONFIG_TPM=y CONFIG_TCG=y CONFIG_ALPHA=y" failed with status 1.

A full log can be found at /Users/tylerjaacks/Desktop/qemu/build/meson-logs/meson-log.txt
```

```
python minikconf.py --defconfig alpha-softmmu-config-devices.mak /Users/tylerjaacks/Desktop/qemu/build/meson-private/alpha-softmmu-config-devices.mak.d /Users/tylerjaacks/Desktop/qemu/configs/devices/alpha-softmmu/default.mak /Users/tylerjaacks/Desktop/qemu/Kconfig CONFIG_TPM=y CONFIG_TCG=y CONFIG_ALPHA=y
Traceback (most recent call last):
  File "/Users/tylerjaacks/Desktop/qemu/scripts/minikconf.py", line 703, in <module>
    config = data.compute_config()
  File "/Users/tylerjaacks/Desktop/qemu/scripts/minikconf.py", line 253, in compute_config
    clause.process()
  File "/Users/tylerjaacks/Desktop/qemu/scripts/minikconf.py", line 199, in process
    if self.cond.evaluate():
  File "/Users/tylerjaacks/Desktop/qemu/scripts/minikconf.py", line 135, in evaluate
    raise KconfigDataError('cycle found including %s' % self)
__main__.KconfigDataError: cycle found including IPOD_TOUCH
```

**Comment by CodeAsm** [comment]
Similiar issue on Linux Arch, ive yet to determine the more exact cause. often I find these problems on Arch due to using the latest (and greatest) tools, (arch being rolling release). maybe a slightly older compiler toolset may help. this isnt ment as an answer, but I hope to figure out how to compile this specific fork of qemu aswell (the normal unmodified version compiled?!?)

**Comment by TylerJaacks** [comment]
I get this same error when trying to compile this program on Windows via MSYS2.

**Comment by RemoPro** [comment]
I have the following Error when I try to configure qemu with macOS Monterey 12.6.6

ERROR: Cannot find Ninja

**Comment by devos50** [comment]
@RemoPro It looks like you don't have `ninja` installed. Does `brew install ninja` resolve the issue?

**Comment by RemoPro** [comment]
> @RemoPro It looks like you don't have `ninja` installed. Does `brew install ninja` resolve the issue?

I try it now with Ventura 13.3.1. For what's is ninja?

**Comment by RemoPro** [comment]
Now it says the following. Why didn't you prebuild the binary?:

ERROR: "cc" cannot build an executable (is your linker broken?)

**Comment by iOSPrincekin** [comment]
> @RemoPro It looks like you don't have `ninja` installed. Does `brew install ninja` resolve the issue?

no, I installed ninja, but have the same error!

**Comment by LukasMFR** [comment]
> Now it says the following. Why didn't you prebuild the binary?:
> 
> ERROR: "cc" cannot build an executable (is your linker broken?)

I have the same issue as you. And I just can't find a fix... @RemoPro

**Comment by MrDiagnose** [comment]
make sure you followed this for MAC OS x86 https://github.com/devos50/qemu-ios/issues/135#issuecomment-1914756808

**Comment by Mohamedd-12345** [comment]
i have a similar issue on windows 10 21h2 
```
python determined to be '/usr/bin/python3'
python version: Python 3.12.12
mkvenv: Creating non-isolated virtual environment at 'pyvenv'
      0 [main] python3 1595 child_info_fork::abort: unable to map \??\D:\git-sdk-64\usr\lib\python3.12\lib-dynload\_csv.cpython-312-x86_64-cygwin.dll (using D:\git-sdk-64\usr\lib\python3.12\lib-dynload\_csv.cpython-312-x86_64-cygwin.dll), Win32 error 126
                                                                                mkvenv did not complete successfully:
Traceback (most recent call last):
  File "/i/git/qemu-ios/python/scripts/mkvenv.py", line 953, in main
    make_venv(
  File "/i/git/qemu-ios/python/scripts/mkvenv.py", line 393, in make_venv
    builder.create(str(env_dir))
  File "/i/git/qemu-ios/python/scripts/mkvenv.py", line 248, in create
    self.post_post_setup(self._context)
  File "/i/git/qemu-ios/python/scripts/mkvenv.py", line 274, in post_post_setup
    subprocess.run(args, check=True)
  File "/usr/lib/python3.12/subprocess.py", line 548, in run
  File "/usr/lib/python3.12/subprocess.py", line 1026, in __init__
  File "/usr/lib/python3.12/subprocess.py", line 1885, in _execute_child
BlockingIOError: [Errno 11] Resource temporarily unavailable

```
